spring:
  datasource:
    url: jdbc:postgresql://dpg-co8imlol5elc738vhmn0-a.oregon-postgres.render.com/javaNE
    username: admin
    password: 13SLJDwScijqMD7LJNL02zXN6z31Kg6A
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: hallcoder25@gmail.com
    password: apsg asbe qeeb hxsf
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
file:
  upload:
    dir : upload
logging:
  level:
    org.springframework.security: DEBUG
    rw.ac.rca.OnlineShop: TRACE
springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
  api-docs.path: /api-docs

