spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/onlineshop
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
file:
  upload:
    dir : upload
logging:
  level:
    org.springframework.security: DEBUG
    rw.ac.rca.OnlineShop: TRACE
springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
  api-docs.path: /api-docs